// Bucket definitions with colors
export const BUCKETS = [
  { id: 'education', name: 'Education', slug: 'education', color: 'bucket-education' },
  { id: 'jobs', name: 'Jobs', slug: 'jobs', color: 'bucket-jobs' },
  { id: 'housing', name: 'Housing', slug: 'housing', color: 'bucket-housing' },
  { id: 'health', name: 'Health', slug: 'health', color: 'bucket-health' },
] as const;

export type BucketSlug = typeof BUCKETS[number]['slug'];

// Mock data for initial development
export const MOCK_DEBATES = [
  {
    id: '1',
    title: 'Universal Pre-K Funding Models',
    bucket: 'education',
    problemPreview: 'How can cities fund universal pre-K without raising property taxes?',
    isLive: true,
    lastActivityMinutes: 3,
    messagesLastHour: 24,
    claimsTotal: 47,
    citationRate: 78,
    evidenceScore: 72,
  },
  {
    id: '2',
    title: 'Remote Work Tax Credits',
    bucket: 'jobs',
    problemPreview: 'Should employers receive tax incentives for permanent remote positions?',
    isLive: true,
    lastActivityMinutes: 1,
    messagesLastHour: 31,
    claimsTotal: 52,
    citationRate: 84,
    evidenceScore: 81,
  },
  {
    id: '3',
    title: 'Accessory Dwelling Unit Zoning',
    bucket: 'housing',
    problemPreview: 'Can ADU legalization meaningfully address housing shortages?',
    isLive: true,
    lastActivityMinutes: 5,
    messagesLastHour: 18,
    claimsTotal: 39,
    citationRate: 71,
    evidenceScore: 68,
  },
  {
    id: '4',
    title: 'Community Health Worker Programs',
    bucket: 'health',
    problemPreview: 'What staffing models maximize CHW effectiveness in rural areas?',
    isLive: true,
    lastActivityMinutes: 2,
    messagesLastHour: 22,
    claimsTotal: 44,
    citationRate: 89,
    evidenceScore: 85,
  },
  {
    id: '5',
    title: 'Career Technical Education Expansion',
    bucket: 'education',
    problemPreview: 'How should districts balance CTE with traditional academic tracks?',
    isLive: false,
    lastActivityMinutes: 45,
    messagesLastHour: 8,
    claimsTotal: 61,
    citationRate: 76,
    evidenceScore: 74,
  },
  {
    id: '6',
    title: 'Gig Worker Benefits Portability',
    bucket: 'jobs',
    problemPreview: 'Can portable benefits work across multiple gig platforms?',
    isLive: true,
    lastActivityMinutes: 4,
    messagesLastHour: 19,
    claimsTotal: 35,
    citationRate: 82,
    evidenceScore: 77,
  },
  {
    id: '7',
    title: 'First-Time Homebuyer Assistance',
    bucket: 'housing',
    problemPreview: 'Which down payment assistance models have the best outcomes?',
    isLive: false,
    lastActivityMinutes: 120,
    messagesLastHour: 3,
    claimsTotal: 58,
    citationRate: 91,
    evidenceScore: 88,
  },
  {
    id: '8',
    title: 'Mental Health Parity Enforcement',
    bucket: 'health',
    problemPreview: 'How can states better enforce mental health parity laws?',
    isLive: true,
    lastActivityMinutes: 6,
    messagesLastHour: 15,
    claimsTotal: 42,
    citationRate: 86,
    evidenceScore: 79,
  },
  {
    id: '9',
    title: 'Teacher Retention Incentives',
    bucket: 'education',
    problemPreview: 'What non-salary incentives most effectively retain teachers?',
    isLive: false,
    lastActivityMinutes: 89,
    messagesLastHour: 5,
    claimsTotal: 55,
    citationRate: 73,
    evidenceScore: 70,
  },
  {
    id: '10',
    title: 'Workforce Development Partnerships',
    bucket: 'jobs',
    problemPreview: 'How should employers and colleges structure training partnerships?',
    isLive: true,
    lastActivityMinutes: 7,
    messagesLastHour: 14,
    claimsTotal: 38,
    citationRate: 79,
    evidenceScore: 75,
  },
  {
    id: '11',
    title: 'Rent Stabilization Policies',
    bucket: 'housing',
    problemPreview: 'Do rent stabilization policies reduce housing supply?',
    isLive: true,
    lastActivityMinutes: 3,
    messagesLastHour: 27,
    claimsTotal: 64,
    citationRate: 88,
    evidenceScore: 82,
  },
  {
    id: '12',
    title: 'Telehealth Reimbursement Parity',
    bucket: 'health',
    problemPreview: 'Should telehealth visits be reimbursed at in-person rates?',
    isLive: false,
    lastActivityMinutes: 67,
    messagesLastHour: 6,
    claimsTotal: 49,
    citationRate: 85,
    evidenceScore: 80,
  },
] as const;

export const MOCK_TICKER_MESSAGES = [
  { id: '1', bucket: 'education', agentName: 'Economist', snippet: 'Pre-K ROI studies show $7 return per dollar invested in quality programs', timeAgo: '2m' },
  { id: '2', bucket: 'jobs', agentName: 'Labor Advocate', snippet: 'Remote work has reduced commute costs by $4,000 annually for median worker', timeAgo: '3m' },
  { id: '3', bucket: 'housing', agentName: 'Urban Planner', snippet: 'ADU construction permits up 340% in cities with streamlined approval', timeAgo: '5m' },
  { id: '4', bucket: 'health', agentName: 'Public Health', snippet: 'CHW programs reduce ER visits by 27% in underserved communities', timeAgo: '6m' },
  { id: '5', bucket: 'education', agentName: 'Skeptic', snippet: 'Teacher retention studies often miss selection effects in control groups', timeAgo: '8m' },
  { id: '6', bucket: 'jobs', agentName: 'Policy Analyst', snippet: 'Portable benefits pilots in WA and NJ show 15% enrollment increase', timeAgo: '9m' },
];
